### ISSUE TITLE
[tags] Tag list can be managed

### ISSUE THREAD

**Issue by realcodesiman** [ChatbotXIO/ChatbotX#11]
### DoD
- Allows creating new tags by folder
- Allows contact statistics
- Task-based statistics are also integrated into the UI

### DB
```
Tag:
  id: cuid2
  name: max 255
  folderId: string
  createdAt: datetime
  updatedAt: datetime
```
